theme = "balsamiq"
baseurl = "http://docs.balsamiq.com/"
languageCode = "en-us"
title = "Balsamiq Documentation"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
SectionPagesMenu = "main"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Docs"
  
  [blackfriday]
plainIdAnchors = true
