---
theme:  "docs-balsamiq-com"
baseurl:  "//docs.balsamiq.com/"
languageCode:  "en-us"
title:  "Balsamiq Documentation"
MetaDataFormat:  "yaml"
pluralizeListTitles:  false
Paginate:  "50"
PageSize:  "50"
contentdir:  "content"
layoutdir:  "layouts"
publishdir:  "public"

blackfriday:
  plainIdAnchors:  true

taxonomies:
  category:  "categories"
  tag:  "tags"

menu.menudesktop:
  name:  "Desktop"
  identifier:  "desktop"
  url:  "/desktop/"

menu.menumybalsamiq:
  name:  "myBalsamiq"
  identifier:  "mybalsamiq"
  url:  "/mybalsamiq/"
---
